[package]
categories = ["command-line-utilities", "multimedia::encoding"]
name = "asg"
version = "2.0.1"
# documentation = "https://docs.rs/asg"
description = "Convert asciicast v3 recordings to compact animated SVG"
keywords = ["asciinema", "svg", "terminal", "animation", "converter"]

edition.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
anyhow = "1.0"
avt = "0.18"
clap = { workspace = true, features = ["derive"] }
env_logger = "0.11"
log = "0.4"
ruzstd = "0.7.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
reqwest = { version = "0.12", default-features = false, features = [
  "blocking",
  "gzip",
  "rustls-tls",
] }

[target.wasm32-wasip2.dependencies]
waki = "0.5"

[dev-dependencies]
roxmltree = "0.20"
tempfile = "3.10"
