name: CI
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.number || github.run_id }}
  cancel-in-progress: true

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt,clippy
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: typos-cli,taplo-cli
      - run: cargo +nightly x lint

  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    needs: check
    environment: release # Optional: for enhanced security
    permissions:
      id-token: write # Required for OIDC token exchange
      contents: write # Required to push tags and create releases
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: rust-lang/crates-io-auth-action@v1
        id: auth
      - id: release
        run: |
          if git log -1 --pretty=%B | grep "^chore: release v[0-9]\+\.[0-9]\+\.[0-9]\+$";
          then
            VERSION=$(git log -1 --pretty=%B | sed -n 's/^chore: release \(v[0-9]\+\.[0-9]\+\.[0-9]\+\)$/\1/p')
            echo "Detected release version: $VERSION"
            cargo publish
            echo "Published to crates.io"
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          else
            echo "Not a release commit, skipping publish"
            echo "version=" >> $GITHUB_OUTPUT
          fi
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
      - name: Create GitHub Release
        if: ${{ steps.release.outputs.version != '' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.release.outputs.version }}
          generate_release_notes: true
          target_commitish: ${{ github.sha }}
