name: CI
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.number || github.run_id }}
  cancel-in-progress: true

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt,clippy
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: typos-cli,taplo-cli
      - run: cargo +nightly x lint

  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    needs: check
    environment: release # Optional: for enhanced security
    permissions:
      id-token: write # Required for OIDC token exchange
    steps:
      - uses: actions/checkout@v5
      - uses: rust-lang/crates-io-auth-action@v1
        id: auth
      - run: |
          if git log -1 --pretty=%B | grep "^chore(rs-lib): release v[0-9]\+\.[0-9]\+\.[0-9]\+$";
          then
            cargo publish
            echo "Published stable release"
          else
            echo "Not a release commit, skipping publish"
          fi
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
